[[bin]]
name = "gir"
path = "src/main.rs"

[dependencies]
bitflags = "2.9"
env_logger = { version = "0.11", default-features = false }
getopts = "0.2.21"
getter_rules = { package = "fix-getters-rules", version = "0.3.2", default-features = false }
hprof = "0.1"
log = "0.4"
regex = "1.11"
rustdoc-stripper = { git = "https://github.com/GuillaumeGomez/rustdoc-stripper" }
toml = { version = "0.8" , features = ["preserve_order"] }
xml-rs = "0.8"

[lib]
name = "libgir"
path = "src/lib.rs"

[package]
authors = [
	"Evgenii Pashkin <eapashkin@gmail.com>",
	"Gleb Kozyrev <gleb@gkoz.com>",
	"Guillaume Gomez <guillaume1.gomez@gmail.com>",
]
build = "build.rs"
edition = "2024"
exclude = ["Gir*.toml", "tests/**/*", "*.md", "generator.py"]
name = "gir"
version = "0.0.1"

[profile]

[profile.release]
codegen-units = 4
